### ISSUE TITLE
Add cpu/wall time measures

### ISSUE THREAD

**Issue by graeme-a-stewart** [HEP-SF/prmon#1]
`prmon` should collect cpu statistics on the monitored process and its children (similar to `time`, but including the children).

**Comment by amete** [comment]
Hi @graeme-a-stewart,

I'll be happy to look into this particular issue. I think pretty much all the necessary information can be extracted from `/proc/[pid]/stat`. There we have the option to track both the CPU time spent in user code as well as the system (including the children). In terms of what we want to write out, we can simply flush out `utime`, `stime`, `cutime` and `cstime` at each measurement interval.  Along w/ the clock ticks information these should suffice higher level calculations. Is there anything else you think might be useful?

Best,
Serhan

**Comment by graeme-a-stewart** [comment]
Hi @amete - what you propose sounds perfect to me. We don't need anything more than that for now (KISS!).

**Comment by amete** [comment]
Thanks @graeme-a-stewart!

I've started working on this in the https://github.com/HEP-SF/prmon/tree/master-cpu-measurements branch. 

Currently I  simply read the afore mentioned information and write it out in the text file after dividing out by the clock ticks (closest second should be good enough I guess). I don't yet add anything to the JSON. I think there we can simply write out the total values. 

I haven't tested it very rigorously in a multi-threaded/process environment, only with a simple single process CPU burner bubble sort, and what I get is consistent w/ `time`.

Please let me know what you think, many thanks :)

**Comment by graeme-a-stewart** [comment]
Looks pretty good - why don't you add the totals found to the output JSON and create a PR.

**Comment by amete** [comment]
Thanks @graeme-a-stewart! I just updated the code to added the totals to the JSON output. Going to create a PR now.
